### ISSUE TITLE
Is the blob upload secure?

### ISSUE THREAD

**Issue by admande** [marks/truevault.rb#14]
Since a file is temporarily stored on the server, is this a secure, HIPAA-compliant way to upload files?

**Comment by kgautreaux** [comment]
The last commit was over 1 year ago.  I don't believe this is being actively maintained so I wouldn't count on it providing a solid basis for HIPAA compliant messaging.  I am not the maintainer but I don't think it is likely to get attention in the future.

**Comment by admande** [comment]
Any advice? I am rails developer struggling with dealing with upload/download TrueVault blobs. Upload I can do with carrierwave (though I can't save the blob_id if I do that). Download I'm useless on.

**Comment by kgautreaux** [comment]
You could try to look at the fork network.  It appears that [drewbaumann/truevault.rb](https://github.com/drewbaumann/truevault.rb) has a recent commit from March of this year.  Might indicate maintained status.  You could also look at forking and maintaining your own version.

**Comment by marks** [comment]
Original creator here. Happy to accept PRs or add someone as a contributor. I unfortunately don't have any advice on the download to server idea other than putting in place controls to mitigate the risk such as storing on an encrypted disk and regularly wiping caches.

**Comment by aguynamedloren** [comment]
@admande my team had similar concerns regarding HIPAA compliance and server pass-through.  When we integrated with TrueVault, we decided to err on the side of caution and use the [File Upload & Download API](https://docs.truevault.com/files).  With this integration, we send `access_key ` and `signature` to the client, allowing our users to upload and download directly from TrueVault.  No PHI passes through our servers.

I recently had a conversion with a technical contact at TrueVault, and they confirmed our thoughts that PHI cannot pass through non-HIPAA servers.  My understanding is it's because there are no BAA contracts in place with said service providers.
